[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.25'

fs_permissions = [{ access = "read-write", path = "./"}]

[rpc_endpoints]
mode = "${MODE_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"

[etherscan]
mode = { key = "${MODE_ETHERSCAN_API_KEY}", url = "${MODE_ETHERSCAN_VERIFIER_URL}" }
optimism = { key = "${OPTIMISM_ETHERSCAN_API_KEY}", url = "${OPTIMISM_ETHERSCAN_VERIFIER_URL}"}