<<<<<<< HEAD
[fmt]
line_length = 120
tab_width = 2
bracket_spacing = false
int_types = 'long'
quote_style = 'single'
number_underscore = 'thousands'
multiline_func_header = 'params_first'
fs_permissions = [{ access = "read-write", path = "./"}]

[profile.default]
solc = '0.8.23'
src = 'solidity'
test = 'solidity/test'
out = 'out'
libs = ['lib']
fuzz_runs = 1000
optimizer_runs = 10_000
fs_permissions = [{ access = "read-write", path = "./"}]

[profile.optimized]
via_ir = true
out = 'out-via-ir'
fuzz_runs = 5000
fs_permissions = [{ access = "read-write", path = "./"}]

[profile.test]
via_ir = true
out = 'out-via-ir'
fuzz_runs = 5000
src = 'solidity/test'
fs_permissions = [{ access = "read-write", path = "./"}]

=======
[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.27"
evm_version= 'paris'
show_progress = true
no-match-test = "testGas"
no-match-contract = "GaugeFlowE2EFuzzTest"
optimizer = true
optimizer_runs = 200

ffi = true
fs_permissions = [{ access = "read-write", path = "./"}]

[fuzz]
runs = 256
>>>>>>> decimals
